### ISSUE TITLE
/etc/init.d/esgf-httpd bad code

### ISSUE THREAD

**Issue by gerbier** [ESGF/apache-frontend#17]
I had a look at systemd logs after 2.6.5 upgrade on a data-node ( in centos 7)
and I have error messages such

mars 09 09:54:16 esg1.umr-cnrm.fr systemd[1]: Ignoring invalid environment assignment 'export LD_LIBRARY_PATH=/opt/esgf/python/lib:/opt/esgf/python/lib/python2.7:/opt/esgf/python/lib/python2.7/site-packages/...

the problem comes from /etc/init.d/esgf-httpd. I do not understand why apache needs a python configuration

**Comment by pchengi** [comment]
Hi, 
This is because the CoG WSGI instance is started by httpd. If the LD_LIBRARY_PATH does not include our custom python path, the WSGI startup fails, as the system python is not the same as what CoG uses.
